### ISSUE TITLE
Is jupyter really a depedency?

### ISSUE THREAD

**Issue by dlech** [pybricks/pybricksdev#4]
I don't see anywhere we are actually using it directly and it seems like a rather large dependency to force on people who may want to use the library or the command line tool but not use jupyter.

**Comment by dlech** [comment]
Once we publish packages on PyPi, it should be possible to add a cell to a jupyter notebook to install the Pybricks dependencies.

```python
import sys
!{sys.executable} -m pip install pybricks
!{sys.executable} -m pip install pybricksdev
```

Then people can run `jupyter notebook` without having to install poetry or clone this repo.

**Comment by dlech** [comment]
Perhaps even better is to have a one-time setup to create a virtual environment and install it as a jupyter kernel.

```
python3 - m venv pybricks-jupyter-kernel
. pybricks-jupyter-kernel/bin/activate
python -m pip install --upgrade pip
pip install ipykernel
pip install pybricksdev
pip install pybricks
python -m ipykernel install --user --name=pybricks
deactivate
```

Then a juptyer notebook can be started by any means (e.g. using system jupyter on Ubuntu + VS Code with Python extension). The pybricks kernel just needs to be selected in the notebook and everything works, including code completion.

This also has the advantage that if someone tries to open an `.ipynb` file on a system that doesn't have the `pybricks` kernel installed, there will be an error message saying that the kernel is missing.

**Comment by laurensvalk** [comment]
> I don't see anywhere we are actually using it directly and it seems like a rather large dependency to force on people who may want to use the library or the command line tool but not use jupyter.

Yes we are. It’s not only where most of the development is done, but also where all the examples will be. For now, there is just the one notebook in the demo folder.

Jupyter is excellent for this because you don’t even have to make or call async loops. You can simply do this in a cell and run it:

await hub.run(my_file)

And you can even run it again without having to connect again, because the context is preserved. Or use gather to run multiple at once.

Let’s not make it too complicated by having all kinds of different installs for different use cases. Anyone who is worried enough about the disk space used by an extra library within the project folder can just remove it from the dependencies.

If we can make an easy install where you can select the kernel from within the globally installed Jupyter as you suggested above, that’s even better.

**Comment by dlech** [comment]
Don't worry about this too much yet. I'm still learning how it all works. :smile:

**Comment by dlech** [comment]
It looks like `jupyter` is a meta package that is never updated (and so doesn't give us any control over the version of its dependencies). The packages we are actually using are `notebook` an `ipykernel`.
